2024-08-12 21:34:49,129 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-12 23:12:16,259 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:39]
2024-08-13 19:23:37,961 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 19:23:37,970 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 19:23:38,009 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 22:27:13,118 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 22:27:13,146 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 22:27:13,179 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 22:43:44,852 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 22:43:44,895 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-13 22:43:44,916 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-14 00:00:52,320 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-14 01:18:48,177 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-14 04:55:52,244 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:27]
2024-08-14 06:28:04,819 ERROR: Exception on / [POST] [in /usr/lib/python3/dist-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 49, in index
    books = sclite(search_query, Book.query.all())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 40, in sclite
    matching_books = [book for book in books if query in book.title.lower()]
                                                         ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
2024-08-14 06:28:15,167 ERROR: Exception on / [POST] [in /usr/lib/python3/dist-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 49, in index
    books = sclite(search_query, Book.query.all())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 40, in sclite
    matching_books = [book for book in books if query in book.title.lower()]
                                                         ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
2024-08-14 06:30:12,088 ERROR: Exception on / [POST] [in /usr/lib/python3/dist-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 49, in index
    books = sclite(search_query, Book.query.all())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 40, in sclite
    matching_books = [book for book in books if query in book.title.lower()]
                                                         ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
2024-08-14 06:39:54,285 INFO: Bookstore application startup [in /root/GoodBooksBot/app.py:28]
2024-08-14 06:40:00,054 ERROR: Exception on / [GET] [in /usr/lib/python3/dist-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 59, in index
    pagination = books_query.paginate(page, per_page, error_out=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Query.paginate() takes 1 positional argument but 3 positional arguments (and 1 keyword-only argument) were given
2024-08-14 06:40:01,917 ERROR: Exception on / [GET] [in /usr/lib/python3/dist-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 59, in index
    pagination = books_query.paginate(page, per_page, error_out=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Query.paginate() takes 1 positional argument but 3 positional arguments (and 1 keyword-only argument) were given
2024-08-14 06:40:02,851 ERROR: Exception on / [GET] [in /usr/lib/python3/dist-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 59, in index
    pagination = books_query.paginate(page, per_page, error_out=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Query.paginate() takes 1 positional argument but 3 positional arguments (and 1 keyword-only argument) were given
2024-08-14 06:40:03,699 ERROR: Exception on / [GET] [in /usr/lib/python3/dist-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/GoodBooksBot/app.py", line 59, in index
    pagination = books_query.paginate(page, per_page, error_out=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Query.paginate() takes 1 positional argument but 3 positional arguments (and 1 keyword-only argument) were given
